import { Project } from "@/types";

export const projects: Project[] = [
  { title: "Проект 1", category: "statue", image: "/projects/photo_1.webp" },
  { title: "Проект 2", category: "statue", image: "/projects/photo_2.webp" },
  { title: "Проект 3", category: "panel", image: "/projects/photo_3.webp" },
  { title: "Проект 4", category: "panel", image: "/projects/photo_4.webp" },
  { title: "Проект 5", category: "statue", image: "/projects/photo_5.webp" },
  { title: "Проект 6", category: "statue", image: "/projects/photo_6.webp" },
  { title: "Проект 7", category: "statue", image: "/projects/photo_7.webp" },
  { title: "Проект 8", category: "panel", image: "/projects/photo_8.webp" },
  { title: "Проект 9", category: "cornice", image: "/projects/photo_9.webp" },
  { title: "Проект 10", category: "cornice", image: "/projects/photo_10.webp" },
  { title: "Проект 11", category: "molding", image: "/projects/photo_11.webp" },
  { title: "Проект 12", category: "panel", image: "/projects/photo_12.webp" },
  { title: "Проект 13", category: "molding", image: "/projects/photo_13.webp" },
  { title: "Проект 14", category: "molding", image: "/projects/photo_14.webp" },
  { title: "Проект 15", category: "statue", image: "/projects/photo_15.webp" },
  { title: "Проект 16", category: "panel", image: "/projects/photo_16.webp" },
  { title: "Проект 17", category: "panel", image: "/projects/photo_17.webp" },
  { title: "Проект 18", category: "molding", image: "/projects/photo_18.webp" },
  { title: "Проект 19", category: "molding", image: "/projects/photo_19.webp" },
  { title: "Проект 20", category: "cornice", image: "/projects/photo_20.webp" },
  { title: "Проект 21", category: "cornice", image: "/projects/photo_21.webp" },
  { title: "Проект 22", category: "cornice", image: "/projects/photo_22.webp" },
  { title: "Проект 23", category: "cornice", image: "/projects/photo_23.webp" },
  { title: "Проект 24", category: "molding", image: "/projects/photo_24.webp" },
  { title: "Проект 25", category: "statue", image: "/projects/photo_25.webp" },
  { title: "Проект 26", category: "molding", image: "/projects/photo_26.webp" },
  { title: "Проект 27", category: "molding", image: "/projects/photo_27.webp" },
];
